export const RSS_FEEDS: Record<string, { name: string; url: string }[]> = {
  finance: [
    { name: "CNBC Top News", url: "https://www.cnbc.com/id/100003114/device/rss/rss.html" },
    { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/" },
    { name: "Financial Times", url: "https://www.ft.com/rss/home" },
    { name: "Yahoo Finance", url: "https://finance.yahoo.com/news/rssindex" },
    { name: "Bloomberg", url: "https://feeds.bloomberg.com/markets/news.rss" },
    { name: "WSJ Markets", url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml" },
  ],
  politics: [
    { name: "BBC World", url: "http://feeds.bbci.co.uk/news/world/rss.xml" },
    { name: "The Guardian World", url: "https://www.theguardian.com/world/rss" },
    { name: "AP Top News", url: "https://feeds.apnews.com/apf-topnews" },
    { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml" },
    { name: "The Guardian US", url: "https://www.theguardian.com/us-news/rss" },
    { name: "The Guardian Australia", url: "https://www.theguardian.com/australia-news/rss" },
  ],
  australia: [
    { name: "ABC Australia", url: "https://www.abc.net.au/news/feed/51120/rss.xml" },
    { name: "ABC Australia Top Stories", url: "https://www.abc.net.au/news/feed/45910/rss.xml" },
    { name: "The Guardian Australia", url: "https://www.theguardian.com/australia-news/rss" },
    { name: "SMH Top Stories", url: "https://www.smh.com.au/rss/feed.xml" },
    { name: "The Age", url: "https://www.theage.com.au/rss/feed.xml" },
    { name: "ABC Melbourne", url: "https://www.abc.net.au/news/feed/1534/rss.xml" },
  ],
  worldcup: [
    { name: "BBC Sport Football", url: "http://feeds.bbci.co.uk/sport/football/rss.xml" },
    { name: "ESPN FC", url: "https://www.espn.com/espn/rss/soccer/news" },
    { name: "Goal.com", url: "https://www.goal.com/feeds/en/news" },
    { name: "Sky Sports Football", url: "https://www.skysports.com/rss/12040" },
  ],
  sports: [
    { name: "ESPN NFL", url: "https://www.espn.com/espn/rss/nfl/news" },
    { name: "ESPN AFL", url: "https://www.espn.com/espn/rss/afl/news" },
    { name: "AFL.com.au", url: "https://www.afl.com.au/rss-feeds/news" },
    { name: "Reforma Deportes", url: "https://www.reforma.com/rss/deportes.xml" },
    { name: "Record Mexico", url: "https://www.record.com.mx/rss" },
    { name: "MedioTiempo", url: "https://www.mediotiempo.com/feed" },
  ],
  tech: [
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
    { name: "Wired", url: "https://www.wired.com/feed/rss" },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
    { name: "MIT Tech Review", url: "https://www.technologyreview.com/feed/" },
    { name: "Hacker News", url: "https://hnrss.org/frontpage" },
  ],
  banking: [
    { name: "Bloomberg Finance", url: "https://feeds.bloomberg.com/markets/news.rss" },
    { name: "CNBC Finance", url: "https://www.cnbc.com/id/10000664/device/rss/rss.html" },
    { name: "ECB News", url: "https://www.ecb.europa.eu/rss/press.html" },
    { name: "RBA News", url: "https://www.rba.gov.au/rss/rss-cb-speeches.xml" },
    { name: "Financial Times", url: "https://www.ft.com/rss/home" },
    { name: "WSJ Markets", url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml" },
    { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/" },
    { name: "Banking Dive", url: "https://www.bankingdive.com/feeds/news/" },
    { name: "Finextra", url: "https://www.finextra.com/rss/headlines.aspx" },
  ],
  running: [
    { name: "Triathlete Magazine", url: "https://www.triathlete.com/feed/" },
    { name: "Trirating", url: "https://trirating.com/feed/" },
    { name: "SwimSwam", url: "https://swimswam.com/feed/" },
    { name: "Swim England", url: "https://www.swimming.org/swimengland/feed/" },
    { name: "VeloNews", url: "https://velonews.com/feed/" },
    { name: "Cycling Weekly", url: "https://www.cyclingweekly.com/feed" },
    { name: "World Athletics", url: "https://worldathletics.org/rss/news" },
  ],
  business: [
    { name: "SmartCompany", url: "https://www.smartcompany.com.au/feed/" },
    { name: "Dynamic Business", url: "https://dynamicbusiness.com.au/feed" },
    { name: "ABC News", url: "https://www.abc.net.au/news/feed/45910/rss.xml" },
    { name: "Sydney Morning Herald", url: "https://www.smh.com.au/rss/feed.xml" },
    { name: "InnovationAus", url: "https://www.innovationaus.com/feed/" },
    { name: "Startup Daily", url: "https://www.startupdaily.net/feed/" },
    { name: "Guardian Economy", url: "https://www.theguardian.com/business/economics/rss" },
  ],
  latest: [
    { name: "NPR News", url: "https://feeds.npr.org/1001/rss.xml" },
    { name: "BBC Top Stories", url: "http://feeds.bbci.co.uk/news/rss.xml" },
    { name: "AP Top News", url: "https://feeds.apnews.com/apf-topnews" },
    { name: "ABC Australia", url: "https://www.abc.net.au/news/feed/45910/rss.xml" },
    { name: "The Guardian", url: "https://www.theguardian.com/world/rss" },
    { name: "CNBC", url: "https://www.cnbc.com/id/100003114/device/rss/rss.html" },
  ],
};
